[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyProduct("SX1231SKB")]
[assembly: System.Reflection.AssemblyTitle("SX1231 Starter Kit B")]
[assembly: System.Reflection.AssemblyDescription("Enables the evaluation of the Semtech SX1231 chip an integrated transceiver operating in a wide frequency range including the 433, 868 and 915 MHz license-free ISM (Industry Scientific and Medical) frequency band.")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCompany("Semtech")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 Semtech 2011")]
[assembly: System.Runtime.InteropServices.Guid("6214011d-719f-48fa-8661-75e130ef6e00")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.0")]

