[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyFileVersion("1.2.0.0")]
[assembly: System.Reflection.AssemblyCompany("-")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyTitle("SemtechLib.Devices.SX1231")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.InteropServices.Guid("5c4d9cfa-8e37-4788-a9fa-327a0aef01ac")]
[assembly: System.Reflection.AssemblyProduct("SemtechLib.Devices.SX1231")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 - 2010")]
[assembly: System.Reflection.AssemblyTrademark("")]

